version: "3"
services:
  products-server:
    container_name: products-server
    image: server
    restart: always
    build: .
    ports:
      - "9000:9000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ~/data/db:/data/db
    ports:
      - '27017:27017'
